services:
  backend:
    build: ./backend
    ports:
      - "8082:8000"
    volumes:
      - ./backend:/app
    environment:
      - WATCHFILES_FORCE_POLLING=true

  frontend:
    build: ./frontend
    ports:
      - "3002:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
